#!/usr/bin/env th
require('test/test_counter')
require('test/test_dataset')
require('test/test_download')
require('test/test_graph')
require('test/test_heap')
require('test/test_list')
require('test/test_map')
require('test/test_model')
require('test/test_prob_table')
require('test/test_queue')
require('test/test_set')
require('test/test_stack')
require('test/test_tree')
require('test/test_variable_tensor')
require('test/test_vocab')
require('test/test_scorer')
require('test/test_util')
